
export const languages = {
    ts: 'TypeScript',
    tsx: 'TSX',
    js: 'JavaScript',
    jsx: 'JSX',
    py: 'Python',
    java: 'Java',
    cpp: 'C++',
    csharp: 'C#',
    ruby: 'Ruby',
    php: 'PHP',
    swift: 'Swift',
    kotlin: 'Kotlin',
    go: 'Go',
    rs: 'Rust',
    dart: 'Dart',
    scala: 'Scala',
    r: 'R',
    perl: 'Perl',
    lua: 'Lua',
    html: 'HTML',
    css: 'CSS',
    scss: 'SCSS',
    sql: 'SQL',
    json: 'JSON',
    yaml: 'YAML',
    xml: 'XML',
    dockerfile: 'Dockerfile',
}

export const languageKeyToMonacoLanguageMap = {
    ts: 'typescript',
    tsx: 'typescript',
    js: 'javascript',
    jsx: 'javascript',
    py: 'python',
    java: 'java',
    cpp: 'cpp',
    csharp: 'csharp',
    ruby: 'ruby',
    php: 'php',
    swift: 'swift',
    kotlin: 'kotlin',
    go: 'go',
    rs: 'rust',
    dart: 'dart',
    scala: 'scala',
    r: 'r',
    perl: 'perl',
    lua: 'lua',
    html: 'html',
    css: 'css',
    scss: 'scss',
    sql: 'sql',
    json: 'json',
    yaml: 'yaml',
    xml: 'xml'
  }


  export type Ilanguage = keyof typeof languages